[Fix] dockerfile

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,17 +1,33 @@
-# build stage
-FROM  docker.io/node:18 AS build
+# STAGE 1: install
+FROM docker.io/node:lts-alpine AS base
 
-WORKDIR /root
-COPY . /root
+WORKDIR /base
 
-RUN yarn install
+# Install dependencies
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+# STAGE 2: build
+FROM base AS build
+ENV NODE_ENV=production
+WORKDIR /build
+COPY --from=base /base/node_modules ./node_modules
+COPY . .
 RUN yarn build
 
-# final stage
-FROM  docker.io/node:18
+# STAGE 3: app
+FROM base AS app
+WORKDIR /app
 
-WORKDIR /opt/graphql
-COPY --from=build /root/build /opt/graphql
-COPY --from=build /root/.env /opt/graphql/.env
+ENV NODE_ENV=production
+
+COPY --from=build /build/build ./
+COPY --from=build /build/node_modules ./node_modules
+COPY --from=build /build/.env ./.env
 
 CMD ["node", "main.js"]
